install-windowsfeature -name Web-Server -computerName localhost
install-windowsfeature -name Web-WebServer -computerName localhost
install-windowsfeature -name Web-Common-Http -computerName localhost
install-windowsfeature -name Web-Default-Doc -computerName localhost
install-windowsfeature -name Web-Dir-Browsing -computerName localhost
install-windowsfeature -name Web-Http-Errors -computerName localhost
install-windowsfeature -name Web-Static-Content -computerName localhost
install-windowsfeature -name Web-Http-Redirect -computerName localhost
install-windowsfeature -name Web-Health -computerName localhost
install-windowsfeature -name Web-Http-Logging -computerName localhost
install-windowsfeature -name Web-Performance -computerName localhost
install-windowsfeature -name Web-Stat-Compression -computerName localhost
install-windowsfeature -name Web-Security -computerName localhost
install-windowsfeature -name Web-Filtering -computerName localhost
install-windowsfeature -name Web-Windows-Auth -computerName localhost
install-windowsfeature -name Web-App-Dev -computerName localhost
install-windowsfeature -name Web-Net-Ext -computerName localhost
install-windowsfeature -name Web-Net-Ext45 -computerName localhost
install-windowsfeature -name Web-ASP -computerName localhost
install-windowsfeature -name Web-Asp-Net -computerName localhost
install-windowsfeature -name Web-Asp-Net45 -computerName localhost
install-windowsfeature -name Web-ISAPI-Ext -computerName localhost
install-windowsfeature -name Web-ISAPI-Filter -computerName localhost
install-windowsfeature -name Web-Mgmt-Tools -computerName localhost
install-windowsfeature -name Web-Mgmt-Console -computerName localhost
install-windowsfeature -name Web-Mgmt-Compat -computerName localhost
install-windowsfeature -name Web-Metabase -computerName localhost
install-windowsfeature -name Web-Lgcy-Mgmt-Console -computerName localhost
install-windowsfeature -name Web-Lgcy-Scripting -computerName localhost
install-windowsfeature -name Web-WMI -computerName localhost
install-windowsfeature -name Web-Scripting-Tools -computerName localhost
install-windowsfeature -name Web-Mgmt-Service -computerName localhost
install-windowsfeature -name NET-Framework-Features -computerName localhost
install-windowsfeature -name NET-Framework-Core -computerName localhost
install-windowsfeature -name NET-HTTP-Activation -computerName localhost
install-windowsfeature -name NET-Framework-45-Features -computerName localhost
install-windowsfeature -name NET-Framework-45-Core -computerName localhost
install-windowsfeature -name NET-Framework-45-ASPNET -computerName localhost
install-windowsfeature -name NET-WCF-Services45 -computerName localhost
install-windowsfeature -name NET-WCF-HTTP-Activation45 -computerName localhost
install-windowsfeature -name NET-WCF-MSMQ-Activation45 -computerName localhost
install-windowsfeature -name NET-WCF-TCP-PortSharing45 -computerName localhost
